FROM maven:3.6.3-jdk-11 as build
WORKDIR /app/
COPY pom.xml /app/
COPY src/ /app/src/
RUN mvn package

FROM openjdk:11
COPY --from=build /app/target/*.jar /app.jar
EXPOSE 8080/tcp
ENTRYPOINT ["java","-jar","/app.jar"]
