spring:
  datasource:
    url: jdbc:h2:mem:cars
    driverClassName: org.h2.Driver
    username: test
    password: test
  
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2.console.enabled: true

webConfig:
  cors:
    allowedOrigins: http://localhost:1234, http://localhost:1235
